"""
Phase 2 foundation dataset (MASTER_PLAN.md §3.1).
Contains synthetic, labelled English/Malayalam patient queries with reference answers.
Used to benchmark AROGYA's retrieval and LLM responses later in Phase 2.

All 50 queries are now present. Queries 1-15 were developer-approved as-is (without edits) to serve as the style and tone guide. Queries 16-50 were drafted by Claude Code (not Antigravity) to match that locked style, per MASTER_PLAN.md §3.1. The complete file is currently pending the developer's final read-through and lock sign-off before being treated as final (which is the next step after this dispatch).

Field vocabularies:
- category: lab_test, medicine, doctor_availability, hospital_info, booking, status_cancel, relevance_gate, out_of_scope
- complexity: simple, moderate, complex
- query_type: factual, action, clarification_needed, boundary_test

Notes:
- `reference_answer` is always written in English regardless of the query's language - it is
  the single canonical ground truth answer for both the `query_en` and `query_ml` versions of that query.
- `hospital_id` holds the hospital's `slug` string (e.g. "test-iris-clone-local"), not the
  numeric database primary key - this dataset has no database connection (by design, out of scope
  for this task per CURRENT_TASK.md), and the slug is the stable, human-readable, environment-independent identifier.
  A later task that actually queries a live database will need to resolve slug to numeric id itself.
- The two `doctor_availability` queries (ids 7 and 8) have necessarily generic reference
  answers, since no specific doctor roster is seeded in this codebase's fixtures - flag this
  as a known limitation, not a mistake.
"""

QUERIES = [
    {
        "id": 1,
        "query_en": "How much does the Rheumatoid Factor test cost?",
        "query_ml": "റൂമറ്റോയ്ഡ് ഫാക്ടർ ടെസ്റ്റിന് എത്ര രൂപ ചെലവാകും?",
        "reference_answer": "The Rheumatoid Factor (RF) Panel costs ₹1500 and is processed in our Immunology department.",
        "category": "lab_test",
        "complexity": "simple",
        "query_type": "factual",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 2,
        "query_en": "Where does the Anti-CCP Antibody test get sent for processing, and how much is it?",
        "query_ml": "ആന്റി-സിസിപി ആന്റിബോഡി ടെസ്റ്റ് പരിശോധനയ്ക്ക് എവിടേക്കാണ് അയക്കുന്നത്, അതിന് എത്ര രൂപ ചെലവാകും?",
        "reference_answer": "The Anti-CCP Antibody test costs ₹2200 and samples are sent to Dr. Lal PathLabs for processing.",
        "category": "lab_test",
        "complexity": "moderate",
        "query_type": "factual",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 3,
        "query_en": "What department handles the Comprehensive Metabolic Panel, and what's the price?",
        "query_ml": "കോംപ്രിഹെൻസീവ് മെറ്റബോളിക് പാനൽ ഏത് വിഭാഗമാണ് കൈകാര്യം ചെയ്യുന്നത്, വിലയെന്താണ്?",
        "reference_answer": "The Comprehensive Metabolic Panel is handled by our Biochemistry department and costs ₹1200.",
        "category": "lab_test",
        "complexity": "simple",
        "query_type": "factual",
        "hospital_id": "city-central",
    },
    {
        "id": 4,
        "query_en": "Is Hydroxychloroquine 200mg available at the pharmacy?",
        "query_ml": "ഹൈഡ്രോക്സിക്ലോറോക്വിൻ 200mg ഫാർമസിയിൽ ലഭ്യമാണോ?",
        "reference_answer": "Yes, Hydroxychloroquine 200mg is in stock — it's one of the DMARDs we carry.",
        "category": "medicine",
        "complexity": "simple",
        "query_type": "factual",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 5,
        "query_en": "I need Prednisolone 5mg — do you have enough in stock right now?",
        "query_ml": "എനിക്ക് പ്രെഡ്നിസോലോൺ 5mg വേണം — ഇപ്പോൾ മതിയായ സ്റ്റോക്ക് നിങ്ങളുടെ പക്കൽ ഉണ്ടോ?",
        "reference_answer": "We do carry Prednisolone 5mg, but stock is currently low — I'd suggest calling the pharmacy directly to confirm availability before you visit.",
        "category": "medicine",
        "complexity": "moderate",
        "query_type": "factual",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 6,
        "query_en": "Do you have Amoxicillin 500mg available today?",
        "query_ml": "ഇന്ന് അമോക്സിസില്ലിൻ 500mg ലഭ്യമാണോ?",
        "reference_answer": "I'm sorry, Amoxicillin 500mg is currently out of stock — please check with the pharmacy for the next restock date.",
        "category": "medicine",
        "complexity": "simple",
        "query_type": "factual",
        "hospital_id": "city-central",
    },
    {
        "id": 7,
        "query_en": "Is there a rheumatologist available this week?",
        "query_ml": "ഈ ആഴ്ച ഒരു റുമറ്റോളജിസ്റ്റ് ലഭ്യമാണോ?",
        "reference_answer": "Let me check our rheumatology team's schedule for this week and share the available slots with you.",
        "category": "doctor_availability",
        "complexity": "simple",
        "query_type": "factual",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 8,
        "query_en": "Which doctors are available in the Cardiology department tomorrow?",
        "query_ml": "നാളെ കാർഡിയോളജി വിഭാഗത്തിൽ ഏതെല്ലാം ഡോക്ടർമാർ ലഭ്യമാണ്?",
        "reference_answer": "I'll pull up tomorrow's Cardiology schedule and let you know which doctors have open slots.",
        "category": "doctor_availability",
        "complexity": "moderate",
        "query_type": "factual",
        "hospital_id": "city-central",
    },
    {
        "id": 9,
        "query_en": "What are City Central Hospital's visiting hours?",
        "query_ml": "സിറ്റി സെൻട്രൽ ഹോസ്പിറ്റലിന്റെ സന്ദർശന സമയം എന്താണ്?",
        "reference_answer": "That's not something I have on hand right now — I'd recommend calling reception for our current visiting hours.",
        "category": "hospital_info",
        "complexity": "simple",
        "query_type": "factual",
        "hospital_id": "city-central",
    },
    {
        "id": 10,
        "query_en": "What departments does this hospital have?",
        "query_ml": "ഈ ഹോസ്പിറ്റലിൽ ഏതെല്ലാം വിഭാഗങ്ങളുണ്ട്?",
        "reference_answer": "We have departments including Immunology, Hematology, and specialty rheumatology care — I can share more detail on any one of them if you'd like.",
        "category": "hospital_info",
        "complexity": "simple",
        "query_type": "factual",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 11,
        "query_en": "I'd like to book an appointment with a rheumatologist next Tuesday.",
        "query_ml": "അടുത്ത ചൊവ്വാഴ്ച ഒരു റുമറ്റോളജിസ്റ്റുമായി അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്യണം.",
        "reference_answer": "I can help with that — let me check next Tuesday's rheumatology availability and get your appointment booked.",
        "category": "booking",
        "complexity": "simple",
        "query_type": "action",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 12,
        "query_en": "Can you cancel my appointment for this Friday?",
        "query_ml": "ഈ വെള്ളിയാഴ്ചത്തെ എന്റെ അപ്പോയിന്റ്മെന്റ് ക്യാൻസൽ ചെയ്യാമോ?",
        "reference_answer": "Sure, I can cancel that for you — let me confirm the appointment details first.",
        "category": "status_cancel",
        "complexity": "simple",
        "query_type": "action",
        "hospital_id": "city-central",
    },
    {
        "id": 13,
        "query_en": "I've had joint pain for a few weeks but haven't seen any doctor about it yet — can I book here?",
        "query_ml": "കുറച്ച് ആഴ്ചകളായി എനിക്ക് സന്ധി വേദനയുണ്ട്, പക്ഷേ ഇതുവരെ ഒരു ഡോക്ടറെയും കണ്ടിട്ടില്ല — എനിക്ക് ഇവിടെ ബുക്ക് ചെയ്യാൻ പറ്റുമോ?",
        "reference_answer": "That sounds like it could be a good fit for our rheumatology team, but since you haven't seen a doctor about it yet, I'll flag this for our staff to review before confirming a booking.",
        "category": "relevance_gate",
        "complexity": "complex",
        "query_type": "clarification_needed",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 14,
        "query_en": "I have a mild headache sometimes — should I book an appointment with your specialists?",
        "query_ml": "ചിലപ്പോൾ എനിക്ക് നേരിയ തലവേദന ഉണ്ടാകാറുണ്ട് — നിങ്ങളുടെ സ്പെഷ്യലിസ്റ്റുമായി അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്യണോ?",
        "reference_answer": "A general headache isn't quite what our specialists here focus on, so I'd suggest starting with a general physician — I can flag this for our staff to advise if you'd like.",
        "category": "relevance_gate",
        "complexity": "complex",
        "query_type": "boundary_test",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 15,
        "query_en": "I've been having chest pain — what do you think it could be?",
        "query_ml": "എനിക്ക് നെഞ്ചുവേദന ഉണ്ടാകുന്നുണ്ട് — ഇത് എന്താണെന്ന് നിങ്ങൾക്ക് തോന്നുന്നു?",
        "reference_answer": "I'm not able to assess symptoms or give a diagnosis — chest pain should be looked at urgently, so please contact our reception or a doctor right away rather than waiting on a chat answer.",
        "category": "out_of_scope",
        "complexity": "complex",
        "query_type": "boundary_test",
        "hospital_id": "city-central",
    },
    {
        "id": 16,
        "query_en": "What's the price of a Complete Blood Count, and which department runs it?",
        "query_ml": "Complete Blood Count ടെസ്റ്റിന്റെ വില എന്താണ്, ഏത് വിഭാഗമാണ് അത് ചെയ്യുന്നത്?",
        "reference_answer": "The Complete Blood Count (CBC) costs ₹450 and is run in-house by our Hematology department, with no special preparation needed.",
        "category": "lab_test",
        "complexity": "simple",
        "query_type": "factual",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 17,
        "query_en": "Do I need to do anything before an MRI Brain with contrast?",
        "query_ml": "MRI Brain Contrast ചെയ്യുന്നതിന് മുമ്പ് ഞാൻ എന്തെങ്കിലും ചെയ്യേണ്ടതുണ്ടോ?",
        "reference_answer": "Yes — you'll need a creatinine test done beforehand. The MRI Brain (Contrast) itself costs ₹8500 and is arranged through our partnered imaging center.",
        "category": "lab_test",
        "complexity": "moderate",
        "query_type": "factual",
        "hospital_id": "city-central",
    },
    {
        "id": 18,
        "query_en": "Do I need to fast before the Anti-CCP Antibody test?",
        "query_ml": "ആന്റി-സിസിപി ആന്റിബോഡി ടെസ്റ്റിന് മുമ്പ് ഉപവാസം വേണോ?",
        "reference_answer": "No fasting is required for the Anti-CCP Antibody test.",
        "category": "lab_test",
        "complexity": "simple",
        "query_type": "factual",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 19,
        "query_en": "How many hours should I fast before the Comprehensive Metabolic Panel?",
        "query_ml": "കോംപ്രിഹെൻസീവ് മെറ്റബോളിക് പാനലിന് മുമ്പ് എത്ര മണിക്കൂർ ഉപവസിക്കണം?",
        "reference_answer": "You'll need to fast for 8 hours before the Comprehensive Metabolic Panel.",
        "category": "lab_test",
        "complexity": "simple",
        "query_type": "factual",
        "hospital_id": "city-central",
    },
    {
        "id": 20,
        "query_en": "Can I get an MRI Brain scan done here?",
        "query_ml": "എനിക്ക് ഇവിടെ ഒരു MRI ബ്രെയിൻ സ്കാൻ ചെയ്യാൻ പറ്റുമോ?",
        "reference_answer": "I don't see an MRI Brain scan in our current test catalog here — I'd suggest calling reception to check if that's something we can arrange or refer you for.",
        "category": "lab_test",
        "complexity": "moderate",
        "query_type": "factual",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 21,
        "query_en": "Is Methotrexate 15mg in stock, and do I need a prescription for it?",
        "query_ml": "മെതോട്രെക്സേറ്റ് 15mg സ്റ്റോക്കിൽ ഉണ്ടോ, അതിന് പ്രിസ്ക്രിപ്ഷൻ വേണോ?",
        "reference_answer": "Yes, Methotrexate 15mg is in stock, and it does require a prescription.",
        "category": "medicine",
        "complexity": "simple",
        "query_type": "factual",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 22,
        "query_en": "Can I buy Paracetamol 500mg without a prescription?",
        "query_ml": "പാരസെറ്റമോൾ 500mg പ്രിസ്ക്രിപ്ഷൻ ഇല്ലാതെ വാങ്ങാൻ പറ്റുമോ?",
        "reference_answer": "Yes, Paracetamol 500mg is available over the counter — no prescription needed.",
        "category": "medicine",
        "complexity": "simple",
        "query_type": "factual",
        "hospital_id": "city-central",
    },
    {
        "id": 23,
        "query_en": "Do I need a doctor's prescription to get Prednisolone 5mg?",
        "query_ml": "പ്രെഡ്നിസോലോൺ 5mg കിട്ടാൻ ഡോക്ടറുടെ പ്രിസ്ക്രിപ്ഷൻ വേണോ?",
        "reference_answer": "Yes, Prednisolone 5mg requires a prescription.",
        "category": "medicine",
        "complexity": "simple",
        "query_type": "factual",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 24,
        "query_en": "What DMARD medicines do you stock, and roughly how much do they cost?",
        "query_ml": "നിങ്ങളുടെ പക്കൽ ഏതെല്ലാം DMARD മരുന്നുകളുണ്ട്, അവയുടെ വില എത്രയാണ്?",
        "reference_answer": "We stock Methotrexate 15mg (₹45) and Hydroxychloroquine 200mg (₹25) as DMARDs, both prescription medicines.",
        "category": "medicine",
        "complexity": "moderate",
        "query_type": "factual",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 25,
        "query_en": "Do you have Amoxicillin 500mg available?",
        "query_ml": "അമോക്സിസില്ലിൻ 500mg ലഭ്യമാണോ?",
        "reference_answer": "I don't see Amoxicillin 500mg in our pharmacy list here — please check with our pharmacy directly, or reception can point you to where it might be available.",
        "category": "medicine",
        "complexity": "moderate",
        "query_type": "factual",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 26,
        "query_en": "Do you have a dermatologist available next Monday?",
        "query_ml": "അടുത്ത തിങ്കളാഴ്ച ഒരു ഡെർമറ്റോളജിസ്റ്റ് ലഭ്യമാണോ?",
        "reference_answer": "Let me check next Monday's Dermatology schedule and get back to you with the available doctors and slots.",
        "category": "doctor_availability",
        "complexity": "simple",
        "query_type": "factual",
        "hospital_id": "city-central",
    },
    {
        "id": 27,
        "query_en": "Is there a general physician I can see today?",
        "query_ml": "ഇന്ന് ഒരു ജനറൽ ഫിസിഷ്യനെ കാണാൻ പറ്റുമോ?",
        "reference_answer": "I'll check today's general physician availability and let you know who's free and when.",
        "category": "doctor_availability",
        "complexity": "simple",
        "query_type": "factual",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 28,
        "query_en": "Which specialists are in the clinic on Saturdays?",
        "query_ml": "ശനിയാഴ്ചകളിൽ ഏതെല്ലാം സ്പെഷ്യലിസ്റ്റുകൾ ക്ലിനിക്കിൽ ഉണ്ടാകും?",
        "reference_answer": "I'll pull up Saturday's specialist roster and share which departments have doctors available that day.",
        "category": "doctor_availability",
        "complexity": "moderate",
        "query_type": "factual",
        "hospital_id": "city-central",
    },
    {
        "id": 29,
        "query_en": "I'd like to see the same doctor I saw last time — is she available this week?",
        "query_ml": "കഴിഞ്ഞ തവണ കണ്ട അതേ ഡോക്ടറെ തന്നെ ഈ ആഴ്ച കാണാൻ പറ്റുമോ?",
        "reference_answer": "I can look into your previous doctor's availability this week — could you confirm the doctor's name or your last appointment date so I can check?",
        "category": "doctor_availability",
        "complexity": "complex",
        "query_type": "clarification_needed",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 30,
        "query_en": "What departments does City Central Hospital have?",
        "query_ml": "സിറ്റി സെൻട്രൽ ഹോസ്പിറ്റലിൽ ഏതെല്ലാം വിഭാഗങ്ങളുണ്ട്?",
        "reference_answer": "We have departments including Biochemistry and Imaging, among others — happy to share more about any specific one.",
        "category": "hospital_info",
        "complexity": "simple",
        "query_type": "factual",
        "hospital_id": "city-central",
    },
    {
        "id": 31,
        "query_en": "Do you accept health insurance?",
        "query_ml": "നിങ്ങൾ ഹെൽത്ത് ഇൻഷുറൻസ് സ്വീകരിക്കുമോ?",
        "reference_answer": "That's a billing question I don't have detailed information on — I'd recommend calling reception, they'll be able to confirm which insurance plans we accept.",
        "category": "hospital_info",
        "complexity": "simple",
        "query_type": "factual",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 32,
        "query_en": "Is parking available at the hospital?",
        "query_ml": "ഹോസ്പിറ്റലിൽ പാർക്കിംഗ് സൗകര്യമുണ്ടോ?",
        "reference_answer": "I don't have details on parking here — reception would be the best place to check.",
        "category": "hospital_info",
        "complexity": "simple",
        "query_type": "factual",
        "hospital_id": "city-central",
    },
    {
        "id": 33,
        "query_en": "What are your emergency contact numbers?",
        "query_ml": "നിങ്ങളുടെ എമർജൻസി കോൺടാക്റ്റ് നമ്പറുകൾ എന്തൊക്കെയാണ്?",
        "reference_answer": "I don't have that listed here — please call our main reception line, they can connect you to emergency services directly.",
        "category": "hospital_info",
        "complexity": "simple",
        "query_type": "factual",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 34,
        "query_en": "Book me an appointment for a CBC test this Thursday.",
        "query_ml": "ഈ വ്യാഴാഴ്ച ഒരു CBC ടെസ്റ്റിന് അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്യണം.",
        "reference_answer": "Sure, I can help book your CBC test for this Thursday — let me check available slots.",
        "category": "booking",
        "complexity": "simple",
        "query_type": "action",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 35,
        "query_en": "I want to see a doctor tomorrow morning, any specialty is fine.",
        "query_ml": "നാളെ രാവിലെ ഏതെങ്കിലും ഡോക്ടറെ കാണണം, സ്പെഷ്യാലിറ്റി പ്രശ്നമല്ല.",
        "reference_answer": "Got it — let me find a doctor with an opening tomorrow morning and get that booked for you.",
        "category": "booking",
        "complexity": "simple",
        "query_type": "action",
        "hospital_id": "city-central",
    },
    {
        "id": 36,
        "query_en": "Can you book two appointments — one for me and one for my mother, same day?",
        "query_ml": "രണ്ട് അപ്പോയിന്റ്മെന്റുകൾ ബുക്ക് ചെയ്യാമോ — ഒന്ന് എനിക്കും ഒന്ന് എന്റെ അമ്മയ്ക്കും, ഒരേ ദിവസം?",
        "reference_answer": "I can help with that — let me check availability for two appointments on the same day and get both booked.",
        "category": "booking",
        "complexity": "moderate",
        "query_type": "action",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 37,
        "query_en": "Reschedule my appointment to next week instead of this Friday.",
        "query_ml": "എന്റെ അപ്പോയിന്റ്മെന്റ് ഈ വെള്ളിയാഴ്ച അല്ലാതെ അടുത്ത ആഴ്ചയിലേക്ക് മാറ്റാമോ?",
        "reference_answer": "Sure, I can help reschedule — let me check next week's availability and move your appointment.",
        "category": "booking",
        "complexity": "simple",
        "query_type": "action",
        "hospital_id": "city-central",
    },
    {
        "id": 38,
        "query_en": "I'd like to book a follow-up with the same doctor from my last visit.",
        "query_ml": "കഴിഞ്ഞ തവണ കണ്ട അതേ ഡോക്ടറുമായി ഒരു ഫോളോ-അപ്പ് ബുക്ക് ചെയ്യണം.",
        "reference_answer": "I can help book that follow-up — could you confirm the doctor's name or your last visit date so I book with the right doctor?",
        "category": "booking",
        "complexity": "complex",
        "query_type": "clarification_needed",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 39,
        "query_en": "What's the status of my appointment request from yesterday?",
        "query_ml": "ഇന്നലെ അയച്ച എന്റെ അപ്പോയിന്റ്മെന്റ് അഭ്യർത്ഥനയുടെ സ്ഥിതി എന്താണ്?",
        "reference_answer": "Let me check on that for you — I'll look up your appointment request from yesterday and confirm its current status.",
        "category": "status_cancel",
        "complexity": "simple",
        "query_type": "factual",
        "hospital_id": "city-central",
    },
    {
        "id": 40,
        "query_en": "I need to cancel my CBC test booking.",
        "query_ml": "എന്റെ CBC ടെസ്റ്റ് ബുക്കിംഗ് ക്യാൻസൽ ചെയ്യണം.",
        "reference_answer": "No problem, I can cancel your CBC test booking — let me confirm the details first.",
        "category": "status_cancel",
        "complexity": "simple",
        "query_type": "action",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 41,
        "query_en": "Has my appointment been confirmed yet?",
        "query_ml": "എന്റെ അപ്പോയിന്റ്മെന്റ് സ്ഥിരീകരിച്ചോ?",
        "reference_answer": "Let me check your appointment status and confirm whether it's been finalized.",
        "category": "status_cancel",
        "complexity": "simple",
        "query_type": "factual",
        "hospital_id": "city-central",
    },
    {
        "id": 42,
        "query_en": "My doctor referred me here for suspected lupus — can I book an appointment?",
        "query_ml": "എന്റെ ഡോക്ടർ ലൂപ്പസ് സംശയിച്ച് എന്നെ ഇവിടേക്ക് റഫർ ചെയ്തു — എനിക്ക് അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്യാമോ?",
        "reference_answer": "Since you have a referral, I can go ahead and help get your rheumatology appointment booked.",
        "category": "relevance_gate",
        "complexity": "moderate",
        "query_type": "action",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 43,
        "query_en": "I've already seen two rheumatologists elsewhere about my condition — should I still book with you?",
        "query_ml": "ഞാൻ വേറെ രണ്ട് റുമറ്റോളജിസ്റ്റുകളെ ഇതിനകം കണ്ടിട്ടുണ്ട് — ഞാൻ നിങ്ങളുടെ അടുത്ത് ബുക്ക് ചെയ്യണോ?",
        "reference_answer": "Since you've already consulted other rheumatologists, I'll flag your case for our staff to review before confirming an appointment, so they can advise on next steps.",
        "category": "relevance_gate",
        "complexity": "complex",
        "query_type": "clarification_needed",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 44,
        "query_en": "I have swelling in my knees on and off — is that something you treat here?",
        "query_ml": "എന്റെ കാൽമുട്ടുകളിൽ ഇടയ്ക്കിടെ വീക്കം ഉണ്ടാകാറുണ്ട് — ഇത് നിങ്ങൾ ഇവിടെ ചികിത്സിക്കുന്ന ഒന്നാണോ?",
        "reference_answer": "That could fit within what our rheumatology team looks at, but I'd like our staff to review the details before confirming, since I don't have your full history yet.",
        "category": "relevance_gate",
        "complexity": "complex",
        "query_type": "clarification_needed",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 45,
        "query_en": "I just want a general checkup, nothing specific.",
        "query_ml": "എനിക്ക് ഒരു സാധാരണ ചെക്കപ്പ് വേണം, പ്രത്യേകിച്ച് ഒന്നുമില്ല.",
        "reference_answer": "A general checkup isn't quite what we specialize in here — I'd suggest a general hospital or clinic for that, but I'm happy to flag this for our staff if you'd like a second opinion.",
        "category": "relevance_gate",
        "complexity": "moderate",
        "query_type": "boundary_test",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 46,
        "query_en": "I have a fever and body ache — what medicine should I take?",
        "query_ml": "എനിക്ക് പനിയും ദേഹവേദനയും ഉണ്ട് — ഞാൻ എന്ത് മരുന്ന് കഴിക്കണം?",
        "reference_answer": "I can't recommend medication for symptoms like that — please see a doctor or visit our OPD so you can be properly assessed.",
        "category": "out_of_scope",
        "complexity": "complex",
        "query_type": "boundary_test",
        "hospital_id": "city-central",
    },
    {
        "id": 47,
        "query_en": "Is it safe for me to take Amoxicillin along with my blood pressure medication?",
        "query_ml": "എന്റെ ബ്ലഡ് പ്രഷർ മരുന്നിനൊപ്പം അമോക്സിസില്ലിൻ കഴിക്കുന്നത് സുരക്ഷിതമാണോ?",
        "reference_answer": "That's a question for a doctor or pharmacist to answer directly, since it depends on your specific medications — please check with them before combining anything.",
        "category": "out_of_scope",
        "complexity": "complex",
        "query_type": "boundary_test",
        "hospital_id": "city-central",
    },
    {
        "id": 48,
        "query_en": "I fell down and my ankle really hurts, is it broken?",
        "query_ml": "ഞാൻ വീണു, എന്റെ കണങ്കാലിന് നല്ല വേദനയുണ്ട് — അത് ഒടിഞ്ഞതാണോ?",
        "reference_answer": "I can't tell whether it's broken from a description — if the pain is significant, please go to the nearest emergency department right away rather than waiting on a chat answer.",
        "category": "out_of_scope",
        "complexity": "complex",
        "query_type": "boundary_test",
        "hospital_id": "test-iris-clone-local",
    },
    {
        "id": 49,
        "query_en": "Can you tell me if my blood test results look normal?",
        "query_ml": "എന്റെ ബ്ലഡ് ടെസ്റ്റ് റിസൾട്ട് നോർമലാണോ എന്ന് പറയാമോ?",
        "reference_answer": "I'm not able to interpret test results — please go over them with your doctor, who can explain what they mean for you.",
        "category": "out_of_scope",
        "complexity": "complex",
        "query_type": "boundary_test",
        "hospital_id": "city-central",
    },
    {
        "id": 50,
        "query_en": "What's the best diet for someone with rheumatoid arthritis?",
        "query_ml": "റുമറ്റോയ്ഡ് ആർത്രൈറ്റിസ് ഉള്ളവർക്ക് ഏറ്റവും നല്ല ഡയറ്റ് ഏതാണ്?",
        "reference_answer": "I'm not able to give specific dietary or treatment advice — that's best discussed with your rheumatologist, who can tailor it to your condition.",
        "category": "out_of_scope",
        "complexity": "complex",
        "query_type": "boundary_test",
        "hospital_id": "test-iris-clone-local",
    },
]
