"""feature4_relevance_gate_columns

Revision ID: 632d71467bb1
Revises: f3a4b5c6d7e8
Create Date: 2026-07-21 18:54:35.527351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '632d71467bb1'
down_revision: Union[str, None] = 'f3a4b5c6d7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('relevance_reason', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('needs_staff_review', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('hospital', sa.Column('relevance_criteria', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospital', 'relevance_criteria')
    op.drop_column('appointments', 'needs_staff_review')
    op.drop_column('appointments', 'relevance_reason')
    # ### end Alembic commands ###
