"""add_embedding_to_doctors

Revision ID: cadd3b177e0d
Revises: cea080e631b8
Create Date: 2026-04-26 20:56:45.374231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy # <-- ADD THIS LINE

# revision identifiers, used by Alembic.
revision: str = 'cadd3b177e0d'
down_revision: Union[str, None] = 'cea080e631b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.add_column('doctors', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'embedding')

    # ### end Alembic commands ###
